SELECT 
[ORDER].[STATE] AS PROCESS, 
COUNT([ORDER].[ID]) AS ORDERS, 
SUM([CONTENT].[AMOUNT]) AS CONTENTS,
IIF([CNT].[TP] = "EJAZA" , () , ),

SUM([CONTENT].[COST]) AS COST,
SUM([CONTENT].[PAID]) AS PAID,
SUM([CONTENT].[REST]) AS REST


FROM 
[ORDER]  , 
[CONTENT] ,
(
    SELECT [CONTENT].[ORDER_ID] AS OID, 
    [CONTENT].[TYPE] AS TP,   
    SUM ([CONTENT].[AMOUNT]) AS AMNT
    FROM [CONTENT]
    GROUP BY [CONTENT].[ORDER_ID], 
    [CONTENT].[TYPE]
    
) AS [CNT]

WHERE  
[ORDER].[ID] = [CONTENT].[ORDER_ID]
AND [ORDER].[ID] = [CNT].[OID]

GROUP BY 
[ORDER].[STATE] , 
[ORDER].[DEGREE] 
\
ORDER BY 
[ORDER].[DEGREE]
; 