SELECT 
[ORDER].[ID], 
[CNT].[CONTENTS], 
[SHEIKH].[NAME], 
[SHEIKH].[PHONE], 
[SHEIKH].[CITY], 
[SHEIKH].[ADDRESS]
FROM [ORDER], [SHEIKH],

(
SELECT [CNT].[OID] , [CNT].[CONTENTS]
FROM
(

    SELECT [ORDER].[ID] AS [OID], 
    (   [EJ_STMT].[EJ_AMNT] & " - " & 
        [TR_STMT].[TR_AMNT] & " - " & 
        [STP_STMT].[STP_AMNT] & " - " & 
        [MFR_STMT].[MFR_AMNT] & " - " & 
        [DSN_STMT].[DSN_AMNT] & " - " 
    ) AS CONTENTS

    FROM [ORDER],
    (SELECT [CONTENT].[ORDER_ID] AS EJ_ID,SUM ([CONTENT].[AMOUNT]) AS EJ_AMNT FROM [CONTENT] WHERE [CONTENT].[TYPE] = "EJAZA" GROUP BY [CONTENT].[ORDER_ID]) AS EJ_STMT , 
    (SELECT [CONTENT].[ORDER_ID] AS TR_ID,SUM ([CONTENT].[AMOUNT]) AS TR_AMNT FROM [CONTENT] WHERE [CONTENT].[TYPE] = "TREE" GROUP BY [CONTENT].[ORDER_ID]) AS TR_STMT , 
    (SELECT [CONTENT].[ORDER_ID] AS STP_ID,SUM ([CONTENT].[AMOUNT]) AS STP_AMNT FROM [CONTENT] WHERE [CONTENT].[TYPE] = "STAMP" GROUP BY [CONTENT].[ORDER_ID]) AS STP_STMT , 
    (SELECT [CONTENT].[ORDER_ID] AS MFR_ID,SUM ([CONTENT].[AMOUNT]) AS MFR_AMNT FROM [CONTENT] WHERE [CONTENT].[TYPE] = "MFRGH" GROUP BY [CONTENT].[ORDER_ID]) AS MFR_STMT , 
    (SELECT [CONTENT].[ORDER_ID] AS DSN_ID,SUM ([CONTENT].[AMOUNT]) AS DSN_AMNT FROM [CONTENT] WHERE [CONTENT].[TYPE] = "DESIGNING" GROUP BY [CONTENT].[ORDER_ID]) AS DSN_STMT 

    WHERE [ORDER].[ID] = [EJ_STMT].[EJ_ID]
    AND [ORDER].[ID] = [STP_STMT].[STP_ID]
    AND [ORDER].[ID] = [TR_STMT].[TR_ID]
    AND [ORDER].[ID] = [MFR_STMT].[MFR_ID]
    AND [ORDER].[ID] = [DSN_STMT].[DSN_ID]
    
    SELECT [CONTENT].[ORDER_ID] AS OID
    SUM ([CONTENT].[AMOUNT]) AS AMNT
    FROM [CONTENT]
    WHERE [CONTENT].[TYPE] = "EJAZA"
    GROUP BY [CONTENT].[ORDER_ID]
    
) AS [CNT]
GROUP BY [CNT].[OID]

)


WHERE [ORDER].[SHEIKH_NAME] = [SHEIKH].[NAME] 
AND [ORDER].[STATE] = "POST"
AND [ORDER].[ID] = [CNT].[OID]

ORDER BY [ORDER].[ID];