

create table SHEIKH(
    ID NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL ,
    PHONE_1 NUMBER(20) NOT NULL ,
    PHONE_2 NUMBER(20) ,
    COUNTRY VARCHAR2(50) DEFAULT 'مصر',
    CITY VARCHAR2(50) DEFAULT 'القاهرة' NOT NULL, 
    ADDRESS VARCHAR2(2000)
    
);