Attribute VB_Name = "dataModule"
Option Compare Database

Function dataMacro()

    
     DoCmd.OpenQuery "update_contents", acViewNormal, acEdit
     DoCmd.RunSQL ("UPDATE [ORDER], SHEIKH SET [ORDER].SHEIKH_ID = SHEIKH.ID WHERE [ORDER].SHEIKH_NAME = SHEIKH.NAME")
    
     DoCmd.RunSQL ("UPDATE [ORDER], SHEIKH SET [ORDER].SHEIKH_NAME = SHEIKH.NAME WHERE [ORDER].SHEIKH_ID = SHEIKH.ID")
     DoCmd.RunSQL ("UPDATE [ORDER] SET UPDATE_DATE = DATE() WHERE STATE = 'DONE'")
     DoCmd.RunSQL ("INSERT INTO ORDER_HISTORY SELECT * FROM [ORDER] WHERE [ORDER].STATE = 'DONE'")
     DoCmd.RunSQL ("DELETE * FROM [ORDER] WHERE STATE = 'DONE'")

     
    
End Function


Function exportMacro()

    DoCmd.OutputTo acOutputTable, "ORDER", "HTML(*.html)", "\\MAHMOUD-PC\Users\Public\WebApp\data\order.html", False, "", , acExportQualityScreen
    DoCmd.OutputTo acOutputTable, "SHEIKH", "HTML(*.html)", "\\MAHMOUD-PC\Users\Public\WebApp\data\sheikh.html", False, "", , acExportQualityScreen
    DoCmd.OutputTo acOutputQuery, "MANAGE", "HTML(*.html)", "\\MAHMOUD-PC\Users\Public\WebApp\data\manage.html", False, "", , acExportQualityScreen
   
End Function




Sub openSheikh()


    DoCmd.RunSQL ("SELECT * FROM SHEIKH;")

    Dim Foldername As String
    Dim NAME As String
    NAME = "Ì”—«"
    Foldername = "E:\sheikh"

    Shell "C:\WINDOWS\explorer.exe """ & Foldername & "\" & NAME & "", vbNormalFocus
End Sub


Sub CREATE_Sheikh()
  
    Dim Foldername As String
    Dim NAME As String
     Foldername = "E:\sheikh"

    Dim strSQL As String
    Dim rs As DAO.Recordset
    
    strSQL = "SELECT * FROM SHEIKH"
    Set rs = CurrentDb.OpenRecordset(strSQL)
    
    If Not rs.BOF And Not rs.EOF Then
        rs.MoveFirst
        While (Not rs.EOF)
             If Len(Dir(Foldername & "\" & rs.Fields("NAME") & "", vbDirectory)) = 0 Then
                MkDir Foldername & "\" & rs.Fields("NAME") & ""
             End If
            rs.MoveNext
        Wend
    End If

End Sub



Sub try()
  Dim dbs As Database
     
        ' Modify this line to include the path to Northwind
        ' on your computer.
        Set dbs = OpenDatabase("E:\other\otor.accdb")
         
        ' Select all records in the New Customers table
        ' and add them to the Customers table.

             dbs.Execute "INSERT INTO SHEIKH SELECT '≈”„«⁄Ì·√Õ„œ ⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '≈”„«⁄Ì· √Õ„œ Œ«·œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ «»—«ÂÌ„ «·ÕÊ«‘Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ «·„⁄·„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ › ÕÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ ·ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»—«ÂÌ„ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«»Ê „Ãœ «·‰Ã«—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '« ⁄·„ ›Ï »Ì Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ã·«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «»Ê «·‰’—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «»Ê ÷Ì›' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·”⁄œ‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·”Ìœ ’œÌﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·‘—ﬁ«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·’«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·’Ì«œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·⁄—»Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «·‰Õ—«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ «‰Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ »”ÌÊ‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ À«» ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ Ã·Ì·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ Õ—œ«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ —‘«œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ”⁄ÊœÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ”„Ì— ⁄ÿÌ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ”„Ì— ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ‘Õ« Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ’·«Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ⁄«„—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ⁄»œ «·⁄«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ⁄»œ «··Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ⁄·«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ › ÕÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ „ÃœÏ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ „Õ„œ „’ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ „”⁄œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ Â‰œÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ Ê·Ï «··Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Õ„œ ÌÊ”› „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«œ„ ‰«‰«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”«„… ⁄Ê÷' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”·«„ «·‘»—«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”·«„ «·„”—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”·«„ ›«—Êﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”·«„ ›—ÌÕ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”·«„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”„«¡ ”„Ì—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”„«⁄Ì· «Õ„œ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«”„«⁄Ì· „”⁄œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«‘—› «Õ„œ «»Ê ’«»—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«‘—› —„ÌÕ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«‘—› ”⁄œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«‘—› „ﬁ»Ê·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·»‘—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·Õ”‰ «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·Õ’—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ «·„—‘œÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ Œÿ«»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ ⁄»œ «·Õ«›Ÿ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ ⁄»œ «·Õ·Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ ⁄»œ «·—«“ﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ ⁄ﬂ«‘…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ìœ ‰Ã„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·”Ì”Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·‘Õ« ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·ÿÊ«»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«··„⁄Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·„’—Ï «·‘«›⁄Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·„ÂœÏ ’œﬁÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«·Â«„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«· «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«· ”⁄œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«· ”·Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«· „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«‰Ï ⁄»œ «·Õ·Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„«‰Ï „’ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„Ãœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„· ‘ÊﬁÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„· ⁄»œ «·—«“ﬁ ”·«„…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„‰…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„Ì—… «»Ê «·‰’—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«„Ì‰ €«‰„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì„«‰ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì„«‰ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì„‰ ‘»«Ìﬂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì„‰ „«Â—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì„‰ „€«“Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«Ì‰«”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«ÌÂ Â·«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '«ÌÂ«» »œ—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»ŒÌ ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»”«„ ÕÃ«“Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»·«· ⁄»œ «·Â«œÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»Â«¡ «·œÌ‰ ”·Ì„«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»Â«¡ ’»—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '»ÌÃ«œ «·„‰‘«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT ' €—Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT ' Ê›Ìﬁ ÷„—…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ã„«· ≈”„«⁄Ì·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ã„«· —Ã»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ã„«‰… √Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÃÌÂ«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÃÌÂ«‰ ‰⁄Ì„ ›—Ã' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ«“„ ⁄»œ «··Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ«„œ ÿ‰ÿ«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”«„ „Õ„œ «‰Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”«„ „Õ„œ “ﬂÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”«„ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”«‰Ì‰ ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ «·»Ì«—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ Œ·Ì›…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ —Ã»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ ”⁄œ «·«”ÌÊÿÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ ⁄«»œÌ‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ ⁄·Ï Õ”‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ ﬁÌ« Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”‰Ì‰ Ã»—Ì·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ”Ì‰ ‰«’— «·»ÊﬁÌ”Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ·„Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ‰«‰ Õ”Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ‰«‰ “Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ‰«‰ ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Õ‰›Ï „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ«·œ «·Õ”Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ«·œ «·„€—»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ«·œ ⁄“  ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ«·œ ›«—”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ«·œ ›Ê“Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ·«œ «·„’—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Œ·›' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'œ«—  «Ã' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'œ⁄«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—√› ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—«„Ï ﬁ‰œÌ·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—«‰Ì«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—«‰Ì« ’·«Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—»Ì⁄ «·›ÌÊ„Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—‘œÏ ⁄»œ «·Õ„Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—÷« ⁄·Ï œ—ÊÌ‘' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—÷Ê«‰ —«»Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—›⁄  «·»”ÿÊÌ”Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—ÊœÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—Ì‘ ⁄„«—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '—ÌÂ«„ ÊÃÌÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '“ﬂÌ… «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '“Ìœ «·›«—ÊﬁÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '“Ì‰» «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '“Ì‰» Õ‘„ ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”«—… «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”«·„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”«„Õ Ã„«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”«„Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”«Â—…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄œ  Ã„⁄…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄œ ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄Êœ «·‘—Ì›' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄Ìœ «·”⁄ÊœÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄Ìœ «‰Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄Ìœ Ã„⁄…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”⁄Ìœ “⁄Ì„…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”·„Ï ⁄»œ «·‰«’—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”·ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”·ÊÏ ⁄·ÌÊÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”„«Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”„«Õ „Õ„œ ‰Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”„«‰… ⁄’«„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”„Ì— ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”„Ì—…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”‰«¡ ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”Ìœ «Õ„œ ’»—Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”Ìœ ”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”Ìœ… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '”Ì› «·«”·«„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘«œÌ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘—Ì› «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘—Ì› „”⁄Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘⁄»«‰ ⁄‘—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘›«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘ÊﬁÏ «·”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘ÊﬁÏ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘Ê„«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘Ì„«¡ ⁄»œ «·Õ«›Ÿ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘Ì„«¡ „Õ„œ ⁄»œÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‘Ì„«¡ „Õ„œ ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '’«·Õ «Õ„œ ’«·Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '’»«Õ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '’›«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '’·«Õ ⁄ „«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÿ«—ﬁ ⁄»Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÿÂ «·’«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÿÂ ‘«›⁄' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄«∆‘…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄«»œ ‰»ÌÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄«’„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄«Ìœ… «·Œ„Ì”Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄«Ìœ… ⁄ÿÌ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·»«”ÿ Â«‘„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·Õ·Ì„ ⁄ÿ«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·Õ„Ìœ ‘⁄»«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—ƒÊ› „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—Õ„‰ «„Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—Õ„‰ Õ‘„ ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—Õ„‰ ”·Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—Õ„‰ ”„Ì—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—Õ„‰ ‰«ÃÕ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·—“«ﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·”·«„ √»Ê «·‰Ã«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·⁄“Ì“ „’ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·€›«— Ã«»—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·› «Õ ›«—Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «··Â √»Ê «·»—«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «··Â «·ÿ»«Œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «··Â «·€—»«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «··Â ⁄»œ «·€›«—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»œ «·„«·ﬂ ﬁœÌ—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄»Ì—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄“«„ „’ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄“ ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄“  ÿÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄’«„ »ÌÊ„Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄’«„ „»—Êﬂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄’Ê…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄ÿÌ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄›«›' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·« «·‘Õ« ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·« ‘Êﬂ ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·«¡ ’»—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·«¡ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·Ï «·”Ìœ ⁄·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·Ï Õ„œÏ «·‰Õ«”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·Ï ’«·Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·Ï ⁄»œ «·„⁄ÿÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄·Ï ÌÕÌÏ «·“Â—«‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„«— «·‘ÌŒ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„— «·„Ÿ›—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê «»—«ÂÌ„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê «·«‰’«—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê Õ”‰ ⁄›Ì›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê ⁄ﬂ«‘…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê ⁄ÊÌ÷…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄„—Ê „⁄Ê÷' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄‰Ì« ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '⁄ÊÌ”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '€«œ… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›«ÿ„… ⁄»œ «·—«“ﬁ «·”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›«ÿ„… ⁄»œ «·—Õ„‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›«ÿ„… ⁄»œ «··Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›—Õ«‰…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›Ê“Ï ”⁄Ìœ ÂÌﬂ·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '›Ê“Ì… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ﬂ«—„ „Õ„œ ⁄·Ï √Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ﬂ—Ì„… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ﬂ›«›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ﬂÊÀ— Õ”Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '·„Ì«¡ ⁄»œ «·„ﬁ’Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„ƒ„‰ ”⁄œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„«Ãœ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ «»—«ÂÌ„ Õ”‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ «»—«ÂÌ„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ «·Õ”Ì‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ «·œ—⁄' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ «·”Ìœ €‰Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ »“·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ »”ÌÊ‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ »·«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ À«» ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ À—Ê ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Ã»—Ì·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Ã„«· «·”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Ã„«· „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Õ”‰ ’«»—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Õ”Ì‰ ’«·Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ Œ·Ì· „—Ê«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ —»Ì⁄' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ —„÷«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ “ﬂ—Ì«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ”Ìœ ‰›”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ’·«Õ «»Ê ÿ«·»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ’·«Õ «·‘—ﬁ«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄»œ «·ÃÊ«œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄»œ «·”·«„ «Œ—»Ì‘' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄»œ «·⁄“Ì“' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄»œ «··Â' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄»œ —» «·‰»Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄“  «·ﬁ«÷Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄”·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ⁄·Ï „Õ„œ ⁄»œ «·ﬁÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ›—Ìœ “Ê«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ „ Ê·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ „Õ—„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ „Õ„œ ’«·Õ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ „Õ„Êœ ⁄»œ «·ÃÊ«œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ „‰’Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ÂœÂœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„œ ÂÌﬂ·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ «»Ê ÷›‘—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ «·‘ÌŒ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ «·„’—Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ »ﬂ«—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ Ã„«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ —“ﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ ”·«„…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ ”„Ì— »·«·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ ⁄»œ «·»«”ÿ «„Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ ⁄»œ «·œ«Ì„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ ⁄œ”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ „Õ„œ ÿÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Õ„Êœ Â«‘„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„ÕÌ «·œÌ‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„œÌÕ…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„—”Ï »‰ ”·Ì„«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„—›  «·”Ìœ ’«œﬁ «·«œÌ»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„—Ê… ›ƒ«œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„—Ê… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„—Ì„ „’ÿ›Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’»«Õ «·œ”ÊﬁÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’»«Õ «·⁄«∆»' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï «”„«⁄Ì· «»—«ÂÌ„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï «”„«⁄Ì· „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï «·”«œ« Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï «··«ÂÊ‰Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï «·„ÂœÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï ‘⁄·«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï ’·«Õ «·œ”ÊﬁÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï ÿÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï „Õ„œ ”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï „Õ„œ ⁄·Ï „—”Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„’ÿ›Ï „—⁄Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„⁄«– «»—«ÂÌ„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„⁄œ «·‰œ«ÊÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„„œÊÕ «·ﬁ»Ì’Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„‰… «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„‰’Ê— ÂÌﬂ·' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„‰Ï ”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Ï ”„Ì—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '„Ì—›  ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰«œ—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰«œÌ… «·”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰«œÌ… —»Ì⁄' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰»Ì· «Ì„‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰»Ì· ”·«„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ã«…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ã·«¡' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰⁄„«  «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰⁄„… √Õ„œ Õ”‰Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰⁄„… «»—«ÂÌ„ «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰⁄„… Õ”‰ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰⁄„… „Õ„œ Õ”‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê— «»—«ÂÌ„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê— ⁄»œ «·„‰⁄„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê—«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê—« Œ„Ì”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ê—« ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT '‰Ì›Ì‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â«·… «Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â«·… ”—Õ«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â«·… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â«‰Ï «Õ„œ ⁄À„«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â«‰Ï »—ﬂ« ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â»… «»—«ÂÌ„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â»… «‘—› »«·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â»… ”Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â»… €«·Ï' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â»… „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÂœÏ ⁄»œ «·”·«„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â‘«„ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â„  „’ÿ›Ï Õ”‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â‰œ Œ„Ì”' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Â‰œ ⁄ÿÌ Ê' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÂÊ‰—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÂÌ«„ „Õ„œ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÂÌÀ„ ”⁄Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÊÃÌÂ ”„Ì⁄' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê›«¡ ⁄»œ «·Õ„Ìœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê›«¡ ⁄»œ «·„‰⁄„' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê·«¡ Õ”‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê·Ìœ ”·«„…' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê·Ìœ ⁄»œ «·Õ›ÌŸ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ê·Ìœ „Õ„Êœ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ì«”— ”·Ì„«‰' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ì«”— ⁄»œ «·—«“ﬁ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ì«”— ⁄»œ «·‘ﬂÊ—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ì”—«' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'Ì”—Ï ÿÂ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÌÊ”› ’«»—' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"
dbs.Execute "INSERT INTO SHEIKH SELECT 'ÌÊ‰” »«‰œÏ' AS NAME , '«·ﬁ«Â—…' AS CITY , '„’—' AS COUNTRY"

        dbs.Close
End Sub

/
